spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/polar-bookshop-app/external-config.git"
          default-label: master
          timeout: 5
          clone-on-start: true # clone remote repo locally during startup
          force-pull: true # force pulling remote repo and discarding local changes

server:
  port: 8888
  tomcat:
    connection-timeout: 2s # default 20
    keep-alive-timeout: 15s
    threads:
      max: 30 # default 200
      min-spare: 5 # default 10
